### ISSUE TITLE
Input not work inside iron-swipable-pages

### ISSUE THREAD

**Issue by luizalexandrew** [GeoloeG/iron-swipeable-pages#55]
I'm try use a input inside element iron-swipeable-pages but not work, the input seems disabled. do you know explanate the reason of this not work? :(

![captura de tela de 2017-02-20 10-47-50](https://cloud.githubusercontent.com/assets/10445220/23127539/2db63b56-f75a-11e6-9943-6c3dac0dc5d7.png)

**Comment by luizalexandrew** [comment]
The esc-simplequestion element contains an input inside.

![captura de tela de 2017-02-20 10-57-42](https://cloud.githubusercontent.com/assets/10445220/23127878/70ec83fc-f75b-11e6-9858-6794d93f491c.png)

**Comment by luizalexandrew** [comment]
I was able to find the problem, it is related to the class (:host and: host > ::content > *) I will create a pull-request that solves this problem I am facing (the solution is very simple :))

**Comment by MeTaNoV** [comment]
this is weird..., may I see your implementation of `<esc-simplequestion>` and/or a running `jsfiddle` that reproduce the error?

**Comment by luizalexandrew** [comment]
`<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/paper-input/paper-input.html">

<link rel="import" href="../esc-headerquestion/esc-headerquestion.html">

<dom-module id="esc-simplequestion">
	<template>
		<style>
			:host {
				display: block;
			}
			paper-input{
				width: 90%;
				margin: auto;
			}
		</style>

		<esc-headerquestion number="[[number]]" questionpt="[[questionpt]]" questionen="[[questionen]]" required="[[required]]"></esc-headerquestion>
		<paper-input id="input" type="[[type]]" on-keyup="_createResponse" label="[[label]]" value="{{value}}"></paper-input>

	</template>
	<script>
		Polymer({
			is: 'esc-simplequestion',
			properties: {
				type: {
					type: String, 
					value: "text"
				},
				number: {
					type: String,
					value: "#"
				},
				questionpt: {
					type: String
				},
				questionen: {
					type: String
				},
				label:{
					type: String,
					value: "Resposta"
				},
				value:{
					type: String
				},
				response:{
					type: String,
					notify: true
				},
				disabled:{
					type: Boolean,
					observer: '_disabledChanged',
					value: false
				},
				required: {
					type: Boolean,
					observer: '_requiredChanged',
					value: false
				}
			},
			ready: function(){
				if(this.response !== undefined){
					let responseParse = JSON.parse(this.response);
					this.value = responseParse.response;
				}
			},
			_createResponse: function(){
				this.response = new this.Response(this.number, this.value);
			},
			Response: function (number, response) {
			    this.number = number;
			    this.response = response;
			},
			_disabledChanged: function(){
				this.$.input.disabled = this.disabled;
			},
			_requiredChanged: function(){
				this.$.input.required = this.required;
			}
			
		});
	</script>
</dom-module>

`

**Comment by luizalexandrew** [comment]
This is the element

**Comment by luizalexandrew** [comment]
this is the element https://jsfiddle.net/hogjk6mw/1/

**Comment by luizalexandrew** [comment]
the problem occurs with any input (paper-input or only input)

**Comment by luizalexandrew** [comment]
Today i have a new problem. The problem occurs with the last update (1.2.7). i will open a new issue to explanation the what occurred
