### ISSUE TITLE
Problems with gestures in version 1.2.7

### ISSUE THREAD

**Issue by luizalexandrew** [GeoloeG/iron-swipeable-pages#58]
I had a problem with the last update (1.2.7), the gestures for the next screen stopped working and I had to go back to version 1.2.6. The problem happens when I try to drag to the next page, instead of making a smooth transition, the page I pulled back to the starting position and then it goes to the landing page.

The page is this image, when I drag from right to left instead of making the smooth transition as I did in the previous section, the page returns to the starting position and then the second page appears without any animation.

![captura de tela de 2017-03-07 15-28-44](https://cloud.githubusercontent.com/assets/10445220/23671747/18a271d8-034b-11e7-88dc-df5c8c2ecc40.png)
![captura de tela de 2017-03-07 15-30-52](https://cloud.githubusercontent.com/assets/10445220/23671751/1cb9f1f6-034b-11e7-9e54-7548aca72c7f.png)

**Comment by MeTaNoV** [comment]
@luizalexandrew Are you on Polymer Slack? If not join us, it will be easier to find a solution! The last issue was probably introduced with the Carrousel implementation that has been PRed but not tested on my side...
